@echo off
echo Starting runtimes...
echo Starting Brixy Studio Emulator 2021.13.2271
echo ...
echo ...
echo ...
echo ...
echo ...
echo Started
echo Heating up assets...
echo Started server on 192.168.0.147:8000
echo Received heartbeat from Brixy Server Uptime Network... responded with 400 ALIVE
echo Received heartbeat from Brixy Server Uptime Network... responded with 400 ALIVE
echo Received heartbeat from Brixy Server Uptime Network... responded with 400 ALIVE
echo Received heartbeat from Brixy Server Uptime Network... responded with 400 ALIVE
echo Received heartbeat from Brixy Server Uptime Network... responded with 400 ALIVE